/**
 * Generates src/engine/ompOffsets.ts: displacement offsets for a collision-free perfect hash of the
 * OMPEval rank keys of every 5, 6 and 7 card rank multiset (at most four of each rank).
 *
 * Rows of the key space (key >>> 12) are placed densest first at the lowest offset where none of their
 * slots is occupied, as in OMPEval's HandEvaluator. Strict placement (no shared slots even for equal
 * values) makes the same offsets valid for every rule set, whose values differ.
 * Takes a few seconds. Usage: node scripts/gen-omp-offsets.ts
 */

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const RANK_MUL = [0x2000, 0x8001, 0x11000, 0x3a000, 0x91000, 0x176005, 0x366000, 0x41a013, 0x47802e, 0x479068, 0x48c0e4, 0x48f211, 0x494493]
const ROW_SHIFT = 12
const MAX_KEY = 4 * RANK_MUL[12] + 3 * RANK_MUL[11]

const keys: number[] = []
const counts = new Int8Array(13)
const rec = (r: number, n: number) => {
  if (r === 13) {
    if (n >= 5) {
      let key = 0
      for (let i = 0; i < 13; i++) key += counts[i] * RANK_MUL[i]
      keys.push(key)
    }
    return
  }
  for (let k = 0; k <= 4 && n + k <= 7; k++) {
    counts[r] = k
    rec(r + 1, n + k)
  }
  counts[r] = 0
}
rec(0, 0)
if (new Set(keys).size !== keys.length) throw new Error('Rank multipliers are not unique')

const rowCount = (MAX_KEY >>> ROW_SHIFT) + 1
const rows: number[][] = Array.from({ length: rowCount }, () => [])
for (const key of keys) rows[key >>> ROW_SHIFT].push(key)
const order = [...rows.keys()].filter((r) => rows[r].length).sort((a, b) => rows[b].length - rows[a].length || a - b)

const offsets = new Int32Array(rowCount)
const occupied = new Uint8Array(1 << 18)
for (const r of order) {
  for (let off = 0; ; off++) {
    if (rows[r].every((key) => !occupied[(key & 4095) + off])) {
      for (const key of rows[r]) occupied[(key & 4095) + off] = 1
      offsets[r] = off - (r << ROW_SHIFT)
      break
    }
  }
}

const b64 = Buffer.from(offsets.buffer).toString('base64')
const target = fileURLToPath(new URL('../src/engine/ompOffsets.ts', import.meta.url))
writeFileSync(
  target,
  `/** Generated by scripts/gen-omp-offsets.ts: strict (collision free) displacement offsets for OMPEval rank keys of 5..7 cards. */\nexport const OMP_OFFSETS_B64 = '${b64}'\n`,
)
console.log(`Wrote ${keys.length} keys into ${rowCount} rows: ${target}`)
