/**
 * Generates src/engine/preflopRanking.ts: every starting hand class ordered by all-in preflop equity
 * against one random hand and against three random hands (the PokerStove / Equilab convention),
 * for Hold'em and Short Deck (Triton rules).
 *
 * Monte Carlo with worker threads and fixed seeds, so output is reproducible on any machine.
 * Usage: node scripts/gen-preflop-ranking.ts [trialsPerClass]
 */

import { writeFileSync } from 'node:fs'
import { availableParallelism } from 'node:os'
import { fileURLToPath } from 'node:url'
import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads'
import { RULES_SHORT_TRITON, RULES_STANDARD } from '../src/engine/evaluator.ts'
import { Rng } from '../src/engine/rng.ts'
import { classGrid, combosOfClass } from '../src/engine/ranges.ts'

type Deck = 'holdem' | 'shortdeck'
interface Job {
  deck: Deck
  opponents: number
  label: string
  high: number
  low: number
  kind: 'pair' | 'suited' | 'offsuit'
  trials: number
  seed: number
}

function simulate(job: Job): number {
  const rules = job.deck === 'shortdeck' ? RULES_SHORT_TRITON : RULES_STANDARD
  const evalMasks = rules.evalMasks
  const [h1, h2] = combosOfClass(job.high, job.low, job.kind)[0]
  const deck: number[] = []
  for (let c = job.deck === 'shortdeck' ? 16 : 0; c < 52; c++) if (c !== h1 && c !== h2) deck.push(c)
  const rng = new Rng(job.seed)
  const n = deck.length
  const need = job.opponents * 2 + 5
  const m = new Int32Array(4)
  const opp = new Int32Array(job.opponents * 4)
  let equity = 0

  for (let t = 0; t < job.trials; t++) {
    for (let i = 0; i < need; i++) {
      const j = i + rng.nextInt(n - i)
      const tmp = deck[i]
      deck[i] = deck[j]
      deck[j] = tmp
    }
    m[0] = m[1] = m[2] = m[3] = 0
    for (let i = job.opponents * 2; i < need; i++) m[deck[i] & 3] |= 1 << (deck[i] >> 2)
    const heroMasks = [m[0], m[1], m[2], m[3]]
    heroMasks[h1 & 3] |= 1 << (h1 >> 2)
    heroMasks[h2 & 3] |= 1 << (h2 >> 2)
    const hero = evalMasks(heroMasks[0], heroMasks[1], heroMasks[2], heroMasks[3], 7)
    let best = hero
    let winners = 1
    let heroBest = true
    for (let o = 0; o < job.opponents; o++) {
      opp[0] = m[0]
      opp[1] = m[1]
      opp[2] = m[2]
      opp[3] = m[3]
      const a = deck[o * 2]
      const b = deck[o * 2 + 1]
      opp[a & 3] |= 1 << (a >> 2)
      opp[b & 3] |= 1 << (b >> 2)
      const v = evalMasks(opp[0], opp[1], opp[2], opp[3], 7)
      if (v > best) {
        best = v
        winners = 1
        heroBest = false
      } else if (v === best) winners++
    }
    if (heroBest) equity += 1 / winners
  }
  return equity / job.trials
}

if (!isMainThread) {
  const jobs = workerData as Job[]
  for (const job of jobs) parentPort!.postMessage({ label: job.label, deck: job.deck, opponents: job.opponents, equity: simulate(job) })
  process.exit(0)
}

const trials = Number(process.argv[2] ?? 20_000_000)
const jobs: Job[] = []
let seed = 20260914
for (const deck of ['holdem', 'shortdeck'] as const)
  for (const opponents of [1, 3])
    for (const cls of classGrid(deck).flat()) jobs.push({ deck, opponents, ...cls, trials, seed: seed++ })

const threads = Math.max(1, availableParallelism())
const buckets: Job[][] = Array.from({ length: threads }, () => [])
// Interleave so every thread gets a similar mix of cheap (1 opponent) and expensive (3 opponent) jobs.
jobs.forEach((job, i) => buckets[i % threads].push(job))

const results = new Map<string, number>()
const started = Date.now()
await Promise.all(
  buckets.map(
    (bucket) =>
      new Promise<void>((resolve, reject) => {
        const worker = new Worker(fileURLToPath(import.meta.url), { workerData: bucket })
        worker.on('message', (msg: { label: string; deck: Deck; opponents: number; equity: number }) => {
          results.set(`${msg.deck}|${msg.opponents}|${msg.label}`, msg.equity)
          if (results.size % 50 === 0) console.log(`${results.size}/${jobs.length} classes, ${((Date.now() - started) / 1000).toFixed(0)}s`)
        })
        worker.on('error', reject)
        worker.on('exit', () => resolve())
      }),
  ),
)

const table: Record<string, { label: string; equity: number }[]> = {}
for (const deck of ['holdem', 'shortdeck'] as const)
  for (const opponents of [1, 3]) {
    table[`${deck}_vs${opponents}`] = classGrid(deck)
      .flat()
      .map((c) => ({ label: c.label, equity: results.get(`${deck}|${opponents}|${c.label}`)! }))
      .sort((a, b) => b.equity - a.equity || a.label.localeCompare(b.label))
  }

const fmt = (list: { label: string; equity: number }[]) =>
  `[\n${list.map((e) => `    ['${e.label}', ${e.equity.toFixed(5)}],`).join('\n')}\n  ]`

const out = `// Generated by scripts/gen-preflop-ranking.ts (${trials.toLocaleString('en-US')} Monte Carlo trials per class, seeded).
// Do not edit by hand. Each entry: [hand class, all-in preflop equity], strongest first.

export type RankingId = 'vs1' | 'vs3'

export const PREFLOP_EQUITY: Record<'holdem' | 'shortdeck', Record<RankingId, readonly (readonly [string, number])[]>> = {
  holdem: {
    vs1: ${fmt(table.holdem_vs1)},
    vs3: ${fmt(table.holdem_vs3)},
  },
  shortdeck: {
    vs1: ${fmt(table.shortdeck_vs1)},
    vs3: ${fmt(table.shortdeck_vs3)},
  },
}
`
const target = fileURLToPath(new URL('../src/engine/preflopRanking.ts', import.meta.url))
writeFileSync(target, out)
console.log(`Wrote ${target} in ${((Date.now() - started) / 1000).toFixed(0)}s`)
